apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-jenkins-integration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-jenkins-integration
  template:
    metadata:
      labels:
        app: spring-jenkins-integration
    spec:
      containers:
      - name: spring-boot-app
        image: rosjsr/spring-jenkins-integration:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
